media: 
  input: docs/assets
  output: /assets
content:
  - name: homepage
    label: 主页
    path: docs/index.md
    type: file
  - name: collection
    label: 作品资源页面
    path: docs/collection
    type: collection
    filename: "{fields.title}.md"
    fields: 
      - { name: title, label: 标题, type: string, required: true }
      - { name: body, label: 正文, type: rich-text }
  - name: blog
    label: 文章页面
    path: docs/blog
    type: collection
    filename: "{fields.title}.md"
    fields: 
      - { name: title, label: 标题, type: string, required: true }
      - { name: body, label: 正文, type: rich-text }